name: Hyprland Breaking Change Notifier

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
  - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            substituters = https://hyprland.cachix.org
            trusted-public-keys = hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=

      - name: Update
        run: nix flake update

      - name: Build
        run: nix build -L
